name: topsde-v1.0
run-name: 构建 topsde-v1.0 by @${{ github.actor }}
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  BASE_DIR: /home/ngos/workspace/2.6
  PKG_URL: ${{ github.server_url }}/api/packages/topsec/generic
  MVN_VERS: 3.8.6
  JAVA_VERS: 8u144-linux-x64

jobs:
  pre-compile:
    runs-on: 1
    steps:
      - name: 恢复topsec编译机初始状态
        run: |
          echo "恢复编译虚拟机至初始状态"
      - id: finish
        run: |
          echo 'result=true' >> $GITHUB_OUTPUT          
    outputs:
      result: ${{ steps.finish.outputs.result }}  
  
  compile:
    runs-on: 2
    needs: [pre-compile]
    if: ${{ always() && needs.pre-compile.outputs.result == 'true' }} 
    steps:
      - name: 下载代码
        run: |
          echo "下载代码"
          sleep 300

      - id: finish
        run: |
          echo 'result=true' >> $GITHUB_OUTPUT          
    outputs:
      result: ${{ steps.finish.outputs.result }}  

  build:
    runs-on: 2
    needs: [compile]
    if: ${{ always() && needs.compile.outputs.result == 'true' }} 
    steps:
      - name: 编译代码
        run: |
          echo "编译代码"  
          sleep 600        
      - id: finish
        run: |
          echo 'result=true' >> $GITHUB_OUTPUT          
    outputs:
      result: ${{ steps.finish.outputs.result }}  

  post-compile:
    runs-on: 1
    needs: [pre-compile, compile, build]
    if: ${{ always() && needs.pre-compile.outputs.result == 'true' && needs.build.outputs.result != 'true' }} 
    steps:
      - name: 现场保护
        run: |
          echo "现场保护"          
        
  email:
    runs-on: 1
    needs: [pre-compile, compile, build, post-compile]
    if: ${{ always() }} 
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 25
          username: yaodi_cauc@163.com
          password: NPALCSQNNHLRCBKI
          subject: Github Actions job result
          to: cauc.peter@gmail.com
          from: yaodi_cauc@163.com
          body: Build job of test
          